#pragma once
#include <Arduino.h>
#define ARDUINOJSON_USE_LONG_LONG 0
#define ARDUINOJSON_USE_DOUBLE 0
#include <ArduinoJson.h>
#if defined(ESP8266)
#include <ESP8266WiFi.h>
#include <ESPAsyncTCP.h>
#endif
#include <ESPAsyncWebServer.h>
#include <WiFiClient.h>
#include <ESP8266HTTPClient.h>
#include "data_struct.hpp"
DynamicJsonDocument doc(2048);
const char *ssid = USERNAME;
const char *password = PASSWORD;
static const char *Header = "<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<style>\n"
"body {font-family: Arial, Helvetica, sans-serif;}\n"
"\n"
"/* Full-width input fields */\n"
"input[type=text], input[type=password] {\n"
"  width: 100%;\n"
"  padding: 12px 20px;\n"
"  margin: 8px 0;\n"
"  display: inline-block;\n"
"  border: 1px solid #ccc;\n"
"  box-sizing: border-box;\n"
"}\n"
"\n"
"/* Set a style for all buttons */\n"
"button {\n"
"  background-color: #1ecbe1;\n"
"  color: white;\n"
"  padding: 14px 20px;\n"
"  margin: 8px 0;\n"
"  border: none;\n"
"  cursor: pointer;\n"
"  width: 100%;\n"
"}\n"
"\n"
"button:hover {\n"
"  opacity: 0.8;\n"
"}\n"
"\n"
"/* Extra styles for the cancel button */\n"
".cancelbtn {\n"
"  width: auto;\n"
"  padding: 10px 18px;\n"
"  background-color: #f44336;\n"
"}\n"
"\n"
"/* Center the image and position the close button */\n"
".imgcontainer {\n"
"  text-align: center;\n"
"  margin: 24px 0 12px 0;\n"
"  position: relative;\n"
"}\n"
"\n"
"img.avatar {\n"
"  width: 40%;\n"
"  border-radius: 50%;\n"
"}\n"
"\n"
".container {\n"
"  padding: 16px;\n"
"}\n"
"\n"
"span.psw {\n"
"  float: right;\n"
"  padding-top: 16px;\n"
"}\n"
"\n"
"/* The Modal (background) */\n"
".modal {\n"
"  display: none; /* Hidden by default */\n"
"  position: fixed; /* Stay in place */\n"
"  z-index: 1; /* Sit on top */\n"
"  left: 0;\n"
"  top: 0;\n"
"  width: 100%; /* Full width */\n"
"  height: 100%; /* Full height */\n"
"  overflow: auto; /* Enable scroll if needed */\n"
"  background-color: rgb(0,0,0); /* Fallback color */\n"
"  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */\n"
"  padding-top: 60px;\n"
"}\n"
"\n"
"\n"
"table, th, td {\n"
"  border:solid;\n"
"  border-collapse: collapse;\n"
"  text-align:center;\n"
"}\n"
"\n"
"/* Modal Content/Box */\n"
".modal-content {\n"
"  background-color: #fefefe;\n"
"  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */\n"
"  border: 1px solid #888;\n"
"  width: 80%; /* Could be more or less, depending on screen size */\n"
"}\n"
"\n"
"/* The Close Button (x) */\n"
".close {\n"
"  position: absolute;\n"
"  right: 25px;\n"
"  top: 0;\n"
"  color: #000;\n"
"  font-size: 35px;\n"
"  font-weight: bold;\n"
"}\n"
"\n"
".close:hover,\n"
".close:focus {\n"
"  color: red;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"/* Add Zoom Animation */\n"
".animate {\n"
"  -webkit-animation: animatezoom 0.6s;\n"
"  animation: animatezoom 0.6s\n"
"}\n"
"\n"
"@-webkit-keyframes animatezoom {\n"
"  from {-webkit-transform: scale(0)}\n"
"  to {-webkit-transform: scale(1)}\n"
"}\n"
"\n"
"@keyframes animatezoom {\n"
"  from {transform: scale(0)}\n"
"  to {transform: scale(1)}\n"
"}\n"
"\n"
"/* Change styles for span and cancel button on extra small screens */\n"
"@media screen and (max-width: 300px) {\n"
"  span.psw {\n"
"     display: block;\n"
"     float: none;\n"
"  }\n"
"  .cancelbtn {\n"
"     width: 100%;\n"
"  }\n"
"}\n"
"h2{\n"
"\ttext-align:center;\n"
"}\n"
"\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<h2>Warehouse</h2>\n"
"\n"
"<button onclick=\"document.getElementById('id01').style.display='block'\" style=\"width:auto\" >Details</button>\n"
"\n"
"<div id=\"id01\" class=\"modal\">\n"
"\n"
"  <form class=\"modal-content animate\" action=\"/action_page.php\" method=\"post\">\n"
"  <div class=\"container\" >";